
jobs:
  build:
    executor: python/default
    working_directory: ~/project
    steps:
      - checkout
      - python/install-packages:
          args: truffleHog
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run truffleHog ~/project --regex --json >> ~/project/secrets-check.json
          name: Test secret search 
      - store_artifacts:
          path: ~/project/secrets-check.json
          destination: artifact-file
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build