
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: truffleHog
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run truffleHog https://github.com/dxa4481/truffleHog.git --regex --entropy --json >> secrets-test.json
          name: Test it
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build